version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: alethya_saas_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: alethya_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: alethya_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user_admin:secret_password@db:5432/alethya_db
    depends_on:
      - db

volumes:
  postgres_data: